// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izadohrvbxlljavcroxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6YWRvaHJ2YnhsbGphdmNyb3hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NzMyMzUsImV4cCI6MjA2MTA0OTIzNX0.hAKU93eB2V1u4i4_rZ_kbatolpGTnbLvuZLz4Zk9NTo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);